options(contrasts=c("contr.sum","contr.poly"))
library(pwr)
             
sink("/home/kt-fitz/data/dkl-stats.txt")
data = read.csv("/home/kt-fitz/data/cpp2/alldata2.csv")

se=function(x) sqrt(var(x)/length(x))
sepool = function(x,y) sqrt((var(x)/length(x))+(var(y)/length(y)))
tstat=function(x,y) (mean(y)-mean(x))/sepool(x,y)

#attach(data)
if(FALSE){
apple<-subset(data,data$image==1& data$set!=2 & data$trial<30,select=subject:paa)
banana<-subset(data,data$image==2& data$set!=2 & data$trial<30,select=subject:paa)
house<-subset(data,data$image==3& data$set!=2 & data$trial<30,select=subject:paa)
umbrella<-subset(data,data$image==4& data$set!=2 & data$trial<30,select=subject:paa)
}
apple<-subset(data,data$image==1& data$trial<30,select=subject:paa)
banana<-subset(data,data$image==2& data$trial<30,select=subject:paa)
house<-subset(data,data$image==3& data$trial<30,select=subject:paa)
umbrella<-subset(data,data$image==4& data$trial<30,select=subject:paa)

apple$subject<-factor(apple$subject)
apple$assistance<-factor(apple$assistance)
apple$trial<- factor(apple$trial)
apple$set<-factor(apple$set)
levels(apple$assistance)[1]<-'hsc'
levels(apple$assistance)[2]<-'walls'
cat("***************APPLE***************\n")
cat("############D_KL-TRIAL############ \n")
dklmodela<-aov(apple$dkl~apple$assistance*apple$trial+Error(apple$subject/apple$trial))
means=by(apple$dkl,list(apple$assistance,apple$trial),mean)
ses = by(apple$dkl,list(apple$assistance,apple$trial),se) 

pdf('/home/kt-fitz/data/dkl-appleT.pdf')
    interaction.plot(apple$trial,apple$assistance,apple$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodela))
print(means)
print(ses)
cat("\n")
cat("############D_KL - SET############ \n")
dklmodela<-aov(apple$dkl~apple$assistance*apple$set+Error(apple$subject/apple$set))
means=by(apple$dkl,list(apple$assistance,apple$set),mean)
ses = by(apple$dkl,list(apple$assistance,apple$set),se) 

pdf('/home/kt-fitz/data/dkl-appleS.pdf')
    interaction.plot(apple$set,apple$assistance,apple$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodela))
print(means)
print(ses)
cat("\n\n")
cat("***************Banana***************\n")
banana$assistance<-factor(banana$assistance)
levels(banana$assistance)[1]<-'hsc'
levels(banana$assistance)[2]<-'walls'
cat("############D_KL-TRIAL############ \n")
dklmodelb<-aov(banana$dkl~banana$assistance*banana$trial+Error(banana$subject/banana$trial))
means=by(banana$dkl,list(banana$assistance,banana$trial),mean)
ses = by(banana$dkl,list(banana$assistance,banana$trial),se) 

pdf('/home/kt-fitz/data/dkl-bananaT.pdf')
    interaction.plot(banana$trial,banana$assistance,banana$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodelb))
print(means)
print(ses)
cat("\n")
cat("############D_KL - SET############ \n")
distmodelb<-aov(banana$dkl~banana$assistance*banana$set+Error(banana$subject/banana$set))
means=by(banana$dkl,list(banana$assistance,banana$set),mean)
ses = by(banana$dkl,list(banana$assistance,banana$set),se) 

pdf('/home/kt-fitz/data/dkl-bananaS.pdf')
    interaction.plot(banana$set,banana$assistance,banana$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodelb))
print(means)
print(ses)
cat("\n\n")
cat("***************House***************\n")
house$assistance<-factor(house$assistance)
levels(house$assistance)[1]<-'hsc'
levels(house$assistance)[2]<-'walls'
cat("############D_KL-TRIAL############ \n")
dklmodelh<-aov(house$dkl~house$assistance*house$trial+Error(house$subject/house$trial))
means=by(house$dkl,list(house$assistance,house$trial),mean)
ses = by(house$dkl,list(house$assistance,house$trial),se) 

pdf('/home/kt-fitz/data/dkl-houseT.pdf')
    interaction.plot(house$trial,house$assistance,house$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodelh))
print(means)
print(ses)
cat("\n")
cat("############D_KL - SET############ \n")
dklmodelh<-aov(house$dkl~house$assistance*house$set+Error(house$subject/house$set))
means=by(house$dkl,list(house$assistance,house$set),mean)
ses = by(house$dkl,list(house$assistance,house$set),se) 

pdf('/home/kt-fitz/data/dkl-houseS.pdf')
    interaction.plot(house$set,house$assistance,house$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodelh))
print(means)
print(ses)
cat("\n\n")
cat("***************Umbrella***************\n")
umbrella$assistance<-factor(umbrella$assistance)
levels(umbrella$assistance)[1]<-'hsc'
levels(umbrella$assistance)[2]<-'walls'
cat("############D_KL-TRIAL############ \n")
dklmodelu<-aov(umbrella$dkl~umbrella$assistance*umbrella$trial+Error(umbrella$subject/umbrella$trial))
means=by(umbrella$dkl,list(umbrella$assistance,umbrella$trial),mean)
ses = by(umbrella$dkl,list(umbrella$assistance,umbrella$trial),se) 

pdf('/home/kt-fitz/data/dkl-umbrellaT.pdf')
    interaction.plot(umbrella$trial,umbrella$assistance,umbrella$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodelu))
print(means)
print(ses)
cat("\n")
cat("############D_KL Pixel - SET############ \n")
dklmodelu<-aov(umbrella$dkl~umbrella$assistance*umbrella$set+Error(umbrella$subject/umbrella$set))
means=by(umbrella$dkl,list(umbrella$assistance,umbrella$set),mean)
ses = by(umbrella$dkl,list(umbrella$assistance,umbrella$set),se) 

pdf('/home/kt-fitz/data/dkl-umbrellaS.pdf')
    interaction.plot(umbrella$set,umbrella$assistance,umbrella$dkl,type = "b",pch = c(21,19),ylab="KL Divergence",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(dklmodelu))
print(means)
print(ses)



