options(contrasts=c("contr.sum","contr.poly"))
library(pwr)
             
sink("/home/kt-fitz/data/err-stats.txt")
data = read.csv("/home/kt-fitz/data/cpp2/alldata2.csv")

se=function(x) sqrt(var(x)/length(x))
sepool = function(x,y) sqrt((var(x)/length(x))+(var(y)/length(y)))
tstat=function(x,y) (mean(y)-mean(x))/sepool(x,y)

#attach(data)
if(FALSE){
apple<-subset(data,data$image==1 & data$set!=2 & data$trial<31& data$trial>5,select=subject:paa)
banana<-subset(data,data$image==2& data$set!=2 & data$trial<31& data$trial>5,select=subject:paa)
house<-subset(data,data$image==3& data$set!=2 & data$trial<31& data$trial>5,select=subject:paa)
umbrella<-subset(data,data$image==4& data$set!=2& data$trial>5,select=subject:paa)
}
apple<-subset(data,data$image==1&data$trial<30,select=subject:paa)
banana<-subset(data,data$image==2&data$trial<30,select=subject:paa)
house<-subset(data,data$image==3&data$trial<30,select=subject:paa)
umbrella<-subset(data,data$image==4&data$trial<30,select=subject:paa)

apple$subject<-factor(apple$subject)
apple$assistance<-factor(apple$assistance)
apple$trial<- factor(apple$trial)
apple$set<-factor(apple$set)
levels(apple$assistance)[1]<-'hsc'
levels(apple$assistance)[2]<-'walls'
if(TRUE){
cat("***************APPLE***************\n")
cat("############Distance from Pixel-TRIAL############ \n")
distmodela<-aov(apple$meandTU~apple$assistance*apple$trial+Error(apple$subject/apple$trial))
means=by(apple$meandTU,list(apple$assistance,apple$trial),mean)
ses = by(apple$meandTU,list(apple$assistance,apple$trial),se) 

pdf('/home/kt-fitz/data/meandist-appleT.pdf')
    interaction.plot(apple$trial,apple$assistance,apple$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    lines(c(4,4),c(means[7]-ses[7],means[7]+ses[7])) 
    lines(c(4,4),c(means[8]-ses[8],means[8]+ses[8]))
    lines(c(5,5),c(means[9]-ses[9],means[9]+ses[9])) 
    lines(c(5,5),c(means[10]-ses[10],means[10]+ses[10]))
    lines(c(6,6),c(means[11]-ses[11],means[11]+ses[11])) 
    lines(c(6,6),c(means[12]-ses[12],means[12]+ses[12]))
dev.off()
print(summary(distmodela))
print(means)
print(ses)
cat("\n")
cat("############Distance from Pixel - SET############ \n")
distmodela<-aov(apple$meandTU~apple$assistance*apple$set+Error(apple$subject/apple$set))
means=by(apple$meandTU,list(apple$assistance,apple$set),mean)
ses = by(apple$meandTU,list(apple$assistance,apple$set),se) 

pdf('/home/kt-fitz/data/meandist-appleS.pdf')
    interaction.plot(apple$set,apple$assistance,apple$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
print(means)
print(ses)  
    
dev.off()
print(summary(distmodela))}
cat("\n\n")
cat("***************Banana***************\n")
banana$subject<-factor(banana$subject)
banana$trial<- factor(banana$trial)
banana$set<-factor(banana$set)
banana$assistance<-factor(banana$assistance)
levels(banana$assistance)[1]<-'hsc'
levels(banana$assistance)[2]<-'walls'
cat("############Distance from Pixel-TRIAL############ \n")
distmodelb<-aov(banana$meandTU~banana$assistance*banana$trial+Error(banana$subject/banana$trial))
means=by(banana$meandTU,list(banana$assistance,banana$trial),mean)
ses = by(banana$meandTU,list(banana$assistance,banana$trial),se) 

pdf('/home/kt-fitz/data/meandist-bananaT.pdf')
    interaction.plot(banana$trial,banana$assistance,banana$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    lines(c(4,4),c(means[7]-ses[7],means[7]+ses[7])) 
    lines(c(4,4),c(means[8]-ses[8],means[8]+ses[8]))
    lines(c(5,5),c(means[9]-ses[9],means[9]+ses[9])) 
    lines(c(5,5),c(means[10]-ses[10],means[10]+ses[10]))
    lines(c(6,6),c(means[11]-ses[11],means[11]+ses[11])) 
    lines(c(6,6),c(means[12]-ses[12],means[12]+ses[12]))
dev.off()
print(summary(distmodelb))
print(means)
print(ses)
cat("\n")
cat("############Distance from Pixel - SET############ \n")
distmodelb<-aov(banana$meandTU~banana$assistance*banana$set+Error(banana$subject/banana$set))
means=by(banana$meandTU,list(banana$assistance,banana$set),mean)
ses = by(banana$meandTU,list(banana$assistance,banana$set),se) 

pdf('/home/kt-fitz/data/meandist-bananaS.pdf')
    interaction.plot(banana$set,banana$assistance,banana$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(distmodelb))
cat("\n\n")
cat("***************House***************\n")
house$subject<-factor(house$subject)
house$trial<- factor(house$trial)
house$set<-factor(house$set)
house$assistance<-factor(house$assistance)
levels(house$assistance)[1]<-'hsc'
levels(house$assistance)[2]<-'walls'
cat("############Distance from Pixel-TRIAL############ \n")
distmodelh<-aov(house$meandTU~house$assistance*house$trial+Error(house$subject/house$trial))
means=by(house$meandTU,list(house$assistance,house$trial),mean)
ses = by(house$meandTU,list(house$assistance,house$trial),se) 

pdf('/home/kt-fitz/data/meandist-houseT.pdf')
    interaction.plot(house$trial,house$assistance,house$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    lines(c(4,4),c(means[7]-ses[7],means[7]+ses[7])) 
    lines(c(4,4),c(means[8]-ses[8],means[8]+ses[8]))
    lines(c(5,5),c(means[9]-ses[9],means[9]+ses[9])) 
    lines(c(5,5),c(means[10]-ses[10],means[10]+ses[10]))
    lines(c(6,6),c(means[11]-ses[11],means[11]+ses[11])) 
    lines(c(6,6),c(means[12]-ses[12],means[12]+ses[12]))
dev.off()
print(summary(distmodelh))
print(means)
print(ses)
cat("\n")
cat("############Distance from Pixel - SET############ \n")
distmodelh<-aov(house$meandTU~house$assistance*house$set+Error(house$subject/house$set))
means=by(house$meandTU,list(house$assistance,house$set),mean)
ses = by(house$meandTU,list(house$assistance,house$set),se) 

pdf('/home/kt-fitz/data/meandist-houseS.pdf')
    interaction.plot(house$set,house$assistance,house$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(distmodelh))
print(means)
print(ses)
cat("\n\n")
cat("***************Umbrella***************\n")
umbrella$subject<-factor(umbrella$subject)
umbrella$trial<- factor(umbrella$trial)
umbrella$set<-factor(umbrella$set)
umbrella$assistance<-factor(umbrella$assistance)
levels(umbrella$assistance)[1]<-'hsc'
levels(umbrella$assistance)[2]<-'walls'
cat("############Distance from Pixel-TRIAL############ \n")
distmodelu<-aov(umbrella$meandTU~umbrella$assistance*umbrella$trial+Error(umbrella$subject/umbrella$trial))
means=by(umbrella$meandTU,list(umbrella$assistance,umbrella$trial),mean)
ses = by(umbrella$meandTU,list(umbrella$assistance,umbrella$trial),se) 

pdf('/home/kt-fitz/data/meandist-umbrellaT.pdf')
    interaction.plot(umbrella$trial,umbrella$assistance,umbrella$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Trial")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    lines(c(4,4),c(means[7]-ses[7],means[7]+ses[7])) 
    lines(c(4,4),c(means[8]-ses[8],means[8]+ses[8]))
    lines(c(5,5),c(means[9]-ses[9],means[9]+ses[9])) 
    lines(c(5,5),c(means[10]-ses[10],means[10]+ses[10]))
    lines(c(6,6),c(means[11]-ses[11],means[11]+ses[11])) 
    lines(c(6,6),c(means[12]-ses[12],means[12]+ses[12]))
dev.off()
print(summary(distmodelu))
print(means)
print(ses)
cat("\n")
cat("############Distance from Pixel - SET############ \n")
distmodelu<-aov(umbrella$meandTU~umbrella$assistance*umbrella$set+Error(umbrella$subject/umbrella$set))
means=by(umbrella$meandTU,list(umbrella$assistance,umbrella$set),mean)
ses = by(umbrella$meandTU,list(umbrella$assistance,umbrella$set),se) 

pdf('/home/kt-fitz/data/meandist-umbrellaS.pdf')
    interaction.plot(umbrella$set,umbrella$assistance,umbrella$meandTU,type = "b",pch = c(21,19),ylab="Mean Distance",xlab="Set")
    lines(c(1,1),c(means[1]-ses[1],means[1]+ses[1])) 
    lines(c(1,1),c(means[2]-ses[2],means[2]+ses[2]))
    lines(c(2,2),c(means[3]-ses[3],means[3]+ses[3])) 
    lines(c(2,2),c(means[4]-ses[4],means[4]+ses[4]))
    lines(c(3,3),c(means[5]-ses[5],means[5]+ses[5])) 
    lines(c(3,3),c(means[6]-ses[6],means[6]+ses[6]))
    
dev.off()
print(summary(distmodelu))
print(means)
print(ses)


